[package]
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["command-line-utilities"]
description = "termscp is a feature rich terminal file transfer and explorer with support for SCP/SFTP/FTP/S3"
edition = "2021"
homepage = "https://termscp.veeso.dev"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = [
  "scp-client",
  "sftp-client",
  "ftp-client",
  "winscp",
  "command-line-utility",
]
license = "MIT"
name = "termscp"
readme = "README.md"
repository = "https://github.com/veeso/termscp"
version = "0.13.0"

[package.metadata.rpm]
package = "termscp"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
termscp = { path = "/usr/bin/termscp" }

[package.metadata.deb]
maintainer = "Christian Visintin <christian.visintin@veeso.dev>"
copyright = "2022, Christian Visintin <christian.visintin@veeso.dev>"
extended-description-file = "docs/misc/README.deb.txt"

[[bin]]
name = "termscp"
path = "src/main.rs"

[dependencies]
aes = "0.8"
argh = "^0.1"
base64 = "^0.22"
bitflags = "^2.1"
bytesize = "^1.1"
cbc = { version = "0.1", features = ["std"] }
chrono = "^0.4"
content_inspector = "^0.2"
dirs = "^5.0"
edit = "^0.1"
filetime = "^0.2"
hostname = "^0.3"
keyring = { version = "^2.0", optional = true }
lazy-regex = "^3.1"
lazy_static = "^1.4"
log = "^0.4"
magic-crypt = "^3.1"
notify = "=4.0.17"
notify-rust = { version = "^4.5", default-features = false, features = ["d"] }
open = "^5.0"
rand = "^0.8.5"
remotefs = "^0.2.0"
remotefs-aws-s3 = { version = "^0.2.4", default-features = false, features = [
  "find",
  "rustls",
] }
remotefs-webdav = "^0.1.1"
rpassword = "^7.0"
self_update = { version = "^0.37", default-features = false, features = [
  "rustls",
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
] }
serde = { version = "^1", features = ["derive"] }
simplelog = "^0.12"
ssh2-config = "^0.2"
tempfile = "^3.4"
thiserror = "^1"
toml = "^0.8"
tui-realm-stdlib = "^1.3.1"
tuirealm = "^1.9.1"
unicode-width = "^0.1"
version-compare = "^0.1"
whoami = "^1.4"
wildmatch = "^2.1"

[dev-dependencies]
pretty_assertions = "^1.3"
serial_test = "^3"

[build-dependencies]
cfg_aliases = "0.2"

[features]
default = ["smb", "with-keyring"]
github-actions = []
with-keyring = ["keyring"]
smb = ["remotefs-smb"]

[target."cfg(not(target_os = \"macos\"))".dependencies]
remotefs-smb = { version = "^0.2", optional = true }

[target."cfg(target_family = \"windows\")"]
[target."cfg(target_family = \"windows\")".dependencies]
remotefs-ftp = { version = "^0.1.2", features = ["native-tls"] }
remotefs-ssh = "^0.2"

[target."cfg(target_family = \"unix\")"]
[target."cfg(target_family = \"unix\")".dependencies]
remotefs-ftp = { version = "^0.1.2", features = ["vendored", "native-tls"] }
remotefs-ssh = { version = "^0.2", features = ["ssh2-vendored"] }
users = "0.11.0"

[profile.dev]
incremental = true

[profile.release]
strip = true

[profile.minsize]
inherits = "release"
lto = true
opt-level = "z"
panic = "abort"
strip = true
